// <auto-generated />
namespace _1911066528_BuiXuanHai_Bigschool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Innit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Innit));
        
        string IMigrationMetadata.Id
        {
            get { return "202203221226392_Innit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
